name: 'Bump Version with Bash'
inputs:
  PATH:  
    description: 'path of VERSION file'
    required: true
    default: './VERSION'
  STEP:  
    description: 'STEP to contruct VERSION'
    required: true
    default: 'patch'
outputs:
  value: 
    description: 'value of new VERSION'
runs:
  using: 'node12'
  main: "main.js"